name: Deploy Infrastructure

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY_BASE64 }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      
      - name: Configure Google Cloud credentials
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > /tmp/service-account-key.json
          gcloud auth activate-service-account --key-file=/tmp/service-account-key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
      
      - name: Deploy
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/service-account-key.json
        run: |
          terraform init
          terraform plan
          terraform apply -auto-approve
