name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_SA_KEY_BASE64 }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Decode and Export GCP credentials to file
        run: |
          echo "${{ secrets.GCP_SA_KEY_BASE64 }}" | base64 --decode > "${HOME}/gcp-key.json"
          cat "${HOME}/gcp-key.json" # Verificar el contenido del archivo
        shell: bash

      - name: Validate JSON format
        run: |
          python -m json.tool < "${HOME}/gcp-key.json"
        shell: bash


      - name: Initialize Terraform
        run: terraform init
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "${HOME}/gcp-key.json"

      - name: Import existing resources
        run: bash scripts/import_existing_resources.sh
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "${HOME}/gcp-key.json"
          DATA_BUCKET_NAME: ${{ secrets.DATA_BUCKET_NAME }}
          FUNCTION_BUCKET_NAME: ${{ secrets.FUNCTION_BUCKET_NAME }}
          EXPORT_BUCKET_NAME: ${{ secrets.EXPORT_BUCKET_NAME }}
          REGION: ${{ secrets.GCP_REGION }}

      - name: Apply Terraform
        run: terraform apply -auto-approve -var="credentials_file=${HOME}/gcp-key.json"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "${HOME}/gcp-key.json"
