name: Deploy Infrastructure

on:
  push:
    branches:
      - main
    paths: [ 'TestadosInfra/**' ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY_BASE64 }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./TestadosInfra

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./TestadosInfra

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: ./TestadosInfra
